# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'DesignerMainFrame.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1325, 652)
        MainWindow.setStyleSheet("")
        self.Maincentralwidget = QtWidgets.QWidget(MainWindow)
        self.Maincentralwidget.setObjectName("Maincentralwidget")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.Maincentralwidget)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setContentsMargins(-1, 5, -1, -1)
        self.gridLayout.setObjectName("gridLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.MainNeueFrageButton = QtWidgets.QPushButton(self.Maincentralwidget)
        self.MainNeueFrageButton.setMinimumSize(QtCore.QSize(75, 0))
        self.MainNeueFrageButton.setStyleSheet("")
        self.MainNeueFrageButton.setObjectName("MainNeueFrageButton")
        self.horizontalLayout.addWidget(self.MainNeueFrageButton)
        self.MainLibraryButton = QtWidgets.QPushButton(self.Maincentralwidget)
        self.MainLibraryButton.setMinimumSize(QtCore.QSize(75, 0))
        self.MainLibraryButton.setStyleSheet("")
        self.MainLibraryButton.setObjectName("MainLibraryButton")
        self.horizontalLayout.addWidget(self.MainLibraryButton)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem1)
        self.gridLayout.addLayout(self.horizontalLayout, 2, 3, 1, 1)
        self.MaintreeWidgetFK = QtWidgets.QTreeWidget(self.Maincentralwidget)
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(11)
        self.MaintreeWidgetFK.setFont(font)
        self.MaintreeWidgetFK.setAcceptDrops(True)
        self.MaintreeWidgetFK.setStyleSheet("QPushButton{ ;border: none;}")
        self.MaintreeWidgetFK.setFrameShape(QtWidgets.QFrame.Box)
        self.MaintreeWidgetFK.setFrameShadow(QtWidgets.QFrame.Raised)
        self.MaintreeWidgetFK.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOn)
        self.MaintreeWidgetFK.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAsNeeded)
        self.MaintreeWidgetFK.setSizeAdjustPolicy(QtWidgets.QAbstractScrollArea.AdjustToContents)
        self.MaintreeWidgetFK.setDragDropMode(QtWidgets.QAbstractItemView.DragDrop)
        self.MaintreeWidgetFK.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectItems)
        self.MaintreeWidgetFK.setIndentation(120)
        self.MaintreeWidgetFK.setUniformRowHeights(True)
        self.MaintreeWidgetFK.setColumnCount(0)
        self.MaintreeWidgetFK.setObjectName("MaintreeWidgetFK")
        self.MaintreeWidgetFK.header().setVisible(False)
        self.MaintreeWidgetFK.header().setDefaultSectionSize(0)
        self.MaintreeWidgetFK.header().setMinimumSectionSize(0)
        self.gridLayout.addWidget(self.MaintreeWidgetFK, 1, 1, 1, 1)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setContentsMargins(10, 5, 10, 5)
        self.horizontalLayout_2.setSpacing(10)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label = QtWidgets.QLabel(self.Maincentralwidget)
        self.label.setObjectName("label")
        self.horizontalLayout_2.addWidget(self.label)
        self.mainopenqabutton = QtWidgets.QPushButton(self.Maincentralwidget)
        self.mainopenqabutton.setMinimumSize(QtCore.QSize(75, 0))
        self.mainopenqabutton.setObjectName("mainopenqabutton")
        self.horizontalLayout_2.addWidget(self.mainopenqabutton)
        self.MainSpeichernButton = QtWidgets.QPushButton(self.Maincentralwidget)
        self.MainSpeichernButton.setMinimumSize(QtCore.QSize(75, 0))
        self.MainSpeichernButton.setStyleSheet("")
        self.MainSpeichernButton.setObjectName("MainSpeichernButton")
        self.horizontalLayout_2.addWidget(self.MainSpeichernButton)
        self.MainAbbrechenButton = QtWidgets.QPushButton(self.Maincentralwidget)
        self.MainAbbrechenButton.setMinimumSize(QtCore.QSize(75, 0))
        self.MainAbbrechenButton.setStyleSheet("")
        self.MainAbbrechenButton.setObjectName("MainAbbrechenButton")
        self.horizontalLayout_2.addWidget(self.MainAbbrechenButton)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem2)
        self.MainImportButton = QtWidgets.QPushButton(self.Maincentralwidget)
        self.MainImportButton.setMinimumSize(QtCore.QSize(75, 0))
        self.MainImportButton.setStyleSheet("")
        self.MainImportButton.setObjectName("MainImportButton")
        self.horizontalLayout_2.addWidget(self.MainImportButton)
        self.MainExportButton = QtWidgets.QPushButton(self.Maincentralwidget)
        self.MainExportButton.setMinimumSize(QtCore.QSize(75, 0))
        self.MainExportButton.setStyleSheet("")
        self.MainExportButton.setObjectName("MainExportButton")
        self.horizontalLayout_2.addWidget(self.MainExportButton)
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem3)
        self.label_2 = QtWidgets.QLabel(self.Maincentralwidget)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_2.addWidget(self.label_2)
        self.mainedittreebutton = QtWidgets.QPushButton(self.Maincentralwidget)
        self.mainedittreebutton.setMinimumSize(QtCore.QSize(75, 0))
        self.mainedittreebutton.setObjectName("mainedittreebutton")
        self.horizontalLayout_2.addWidget(self.mainedittreebutton)
        self.maindeletetreebutton = QtWidgets.QPushButton(self.Maincentralwidget)
        self.maindeletetreebutton.setMinimumSize(QtCore.QSize(75, 0))
        self.maindeletetreebutton.setObjectName("maindeletetreebutton")
        self.horizontalLayout_2.addWidget(self.maindeletetreebutton)
        self.gridLayout.addLayout(self.horizontalLayout_2, 2, 1, 1, 1)
        self.formLayout = QtWidgets.QFormLayout()
        self.formLayout.setContentsMargins(5, -1, -1, -1)
        self.formLayout.setVerticalSpacing(15)
        self.formLayout.setObjectName("formLayout")
        self.MainFragebogenLabel = QtWidgets.QLabel(self.Maincentralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.MainFragebogenLabel.sizePolicy().hasHeightForWidth())
        self.MainFragebogenLabel.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.MainFragebogenLabel.setFont(font)
        self.MainFragebogenLabel.setObjectName("MainFragebogenLabel")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.MainFragebogenLabel)
        self.qanamelabel = QtWidgets.QLabel(self.Maincentralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.qanamelabel.sizePolicy().hasHeightForWidth())
        self.qanamelabel.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.qanamelabel.setFont(font)
        self.qanamelabel.setText("")
        self.qanamelabel.setObjectName("qanamelabel")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.qanamelabel)
        self.MainKategorieLabel = QtWidgets.QLabel(self.Maincentralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.MainKategorieLabel.sizePolicy().hasHeightForWidth())
        self.MainKategorieLabel.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.MainKategorieLabel.setFont(font)
        self.MainKategorieLabel.setObjectName("MainKategorieLabel")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.MainKategorieLabel)
        self.catnamelabel = QtWidgets.QLabel(self.Maincentralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.catnamelabel.sizePolicy().hasHeightForWidth())
        self.catnamelabel.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.catnamelabel.setFont(font)
        self.catnamelabel.setText("")
        self.catnamelabel.setObjectName("catnamelabel")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.catnamelabel)
        self.gridLayout.addLayout(self.formLayout, 0, 1, 1, 1)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        spacerItem4 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem4)
        self.MainImportPicture = QtWidgets.QLabel(self.Maincentralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.MainImportPicture.sizePolicy().hasHeightForWidth())
        self.MainImportPicture.setSizePolicy(sizePolicy)
        self.MainImportPicture.setMinimumSize(QtCore.QSize(250, 0))
        self.MainImportPicture.setLineWidth(1)
        self.MainImportPicture.setText("")
        self.MainImportPicture.setObjectName("MainImportPicture")
        self.horizontalLayout_3.addWidget(self.MainImportPicture)
        spacerItem5 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem5)
        self.gridLayout.addLayout(self.horizontalLayout_3, 0, 3, 1, 1)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.mainDropdownQList = QtWidgets.QComboBox(self.Maincentralwidget)
        self.mainDropdownQList.setObjectName("mainDropdownQList")
        self.verticalLayout.addWidget(self.mainDropdownQList)
        self.MainSearchLine = QtWidgets.QLineEdit(self.Maincentralwidget)
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        self.MainSearchLine.setFont(font)
        self.MainSearchLine.setAutoFillBackground(False)
        self.MainSearchLine.setText("")
        self.MainSearchLine.setObjectName("MainSearchLine")
        self.verticalLayout.addWidget(self.MainSearchLine)
        self.MainlistWidgetFragen = QtWidgets.QListWidget(self.Maincentralwidget)
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(11)
        self.MainlistWidgetFragen.setFont(font)
        self.MainlistWidgetFragen.setStyleSheet("")
        self.MainlistWidgetFragen.setFrameShape(QtWidgets.QFrame.Box)
        self.MainlistWidgetFragen.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOn)
        self.MainlistWidgetFragen.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.MainlistWidgetFragen.setDragEnabled(True)
        self.MainlistWidgetFragen.setDragDropMode(QtWidgets.QAbstractItemView.DragOnly)
        self.MainlistWidgetFragen.setObjectName("MainlistWidgetFragen")
        self.verticalLayout.addWidget(self.MainlistWidgetFragen)
        self.gridLayout.addLayout(self.verticalLayout, 1, 3, 1, 1)
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.mainAddfromListButton = QtWidgets.QPushButton(self.Maincentralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.mainAddfromListButton.sizePolicy().hasHeightForWidth())
        self.mainAddfromListButton.setSizePolicy(sizePolicy)
        self.mainAddfromListButton.setMinimumSize(QtCore.QSize(60, 0))
        self.mainAddfromListButton.setMaximumSize(QtCore.QSize(16777215, 16777215))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.mainAddfromListButton.setFont(font)
        self.mainAddfromListButton.setAutoFillBackground(False)
        self.mainAddfromListButton.setStyleSheet("")
        self.mainAddfromListButton.setText("")
        self.mainAddfromListButton.setIconSize(QtCore.QSize(32, 32))
        self.mainAddfromListButton.setObjectName("mainAddfromListButton")
        self.verticalLayout_3.addWidget(self.mainAddfromListButton)
        self.mainDelfromTreeButton = QtWidgets.QPushButton(self.Maincentralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.mainDelfromTreeButton.sizePolicy().hasHeightForWidth())
        self.mainDelfromTreeButton.setSizePolicy(sizePolicy)
        self.mainDelfromTreeButton.setMinimumSize(QtCore.QSize(60, 0))
        self.mainDelfromTreeButton.setText("")
        self.mainDelfromTreeButton.setObjectName("mainDelfromTreeButton")
        self.verticalLayout_3.addWidget(self.mainDelfromTreeButton)
        self.gridLayout.addLayout(self.verticalLayout_3, 1, 2, 1, 1)
        self.gridLayout.setColumnMinimumWidth(3, 220)
        self.gridLayout.setColumnStretch(1, 12)
        self.gridLayout.setColumnStretch(3, 5)
        self.verticalLayout_2.addLayout(self.gridLayout)
        MainWindow.setCentralWidget(self.Maincentralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1325, 21))
        self.menubar.setObjectName("menubar")
        self.menuDatei = QtWidgets.QMenu(self.menubar)
        self.menuDatei.setObjectName("menuDatei")
        self.menuNeu = QtWidgets.QMenu(self.menuDatei)
        self.menuNeu.setObjectName("menuNeu")
        self.menuBearbeiten = QtWidgets.QMenu(self.menubar)
        self.menuBearbeiten.setObjectName("menuBearbeiten")
        self.menuBibliotheken = QtWidgets.QMenu(self.menubar)
        self.menuBibliotheken.setObjectName("menuBibliotheken")
        self.menuHilfe = QtWidgets.QMenu(self.menubar)
        self.menuHilfe.setObjectName("menuHilfe")
        MainWindow.setMenuBar(self.menubar)
        self.actionFragenbibliothek = QtWidgets.QAction(MainWindow)
        self.actionFragenbibliothek.setObjectName("actionFragenbibliothek")
        self.actionFragenkatalogbibliothek = QtWidgets.QAction(MainWindow)
        self.actionFragenkatalogbibliothek.setObjectName("actionFragenkatalogbibliothek")
        self.actionKategorien = QtWidgets.QAction(MainWindow)
        self.actionKategorien.setObjectName("actionKategorien")
        self.actionNeue_Datenbank_hinzuf_gen = QtWidgets.QAction(MainWindow)
        self.actionNeue_Datenbank_hinzuf_gen.setObjectName("actionNeue_Datenbank_hinzuf_gen")
        self.actionDatenbank_anzeigen_hinzuf_gen = QtWidgets.QAction(MainWindow)
        self.actionDatenbank_anzeigen_hinzuf_gen.setObjectName("actionDatenbank_anzeigen_hinzuf_gen")
        self.actionFragebogen_speichern = QtWidgets.QAction(MainWindow)
        self.actionFragebogen_speichern.setObjectName("actionFragebogen_speichern")
        self.actionNeue_Frage_erstellen = QtWidgets.QAction(MainWindow)
        self.actionNeue_Frage_erstellen.setObjectName("actionNeue_Frage_erstellen")
        self.actionNeue_Kategorie_erstellen = QtWidgets.QAction(MainWindow)
        self.actionNeue_Kategorie_erstellen.setObjectName("actionNeue_Kategorie_erstellen")
        self.actionNeuen_Fragebogen_erstellen = QtWidgets.QAction(MainWindow)
        self.actionNeuen_Fragebogen_erstellen.setObjectName("actionNeuen_Fragebogen_erstellen")
        self.actionProgramm_beenden = QtWidgets.QAction(MainWindow)
        self.actionProgramm_beenden.setObjectName("actionProgramm_beenden")
        self.actionProgramm_beenden_2 = QtWidgets.QAction(MainWindow)
        self.actionProgramm_beenden_2.setObjectName("actionProgramm_beenden_2")
        self.actionHilfe_ffnen = QtWidgets.QAction(MainWindow)
        self.actionHilfe_ffnen.setObjectName("actionHilfe_ffnen")
        self.actionDatei_importieren = QtWidgets.QAction(MainWindow)
        self.actionDatei_importieren.setObjectName("actionDatei_importieren")
        self.actionFragebogen_exportieren = QtWidgets.QAction(MainWindow)
        self.actionFragebogen_exportieren.setObjectName("actionFragebogen_exportieren")
        self.actionFragebogen_Kategorien = QtWidgets.QAction(MainWindow)
        self.actionFragebogen_Kategorien.setObjectName("actionFragebogen_Kategorien")
        self.actionNewQuestionnaireCategory = QtWidgets.QAction(MainWindow)
        self.actionNewQuestionnaireCategory.setObjectName("actionNewQuestionnaireCategory")
        self.actionTeste_Session_Log = QtWidgets.QAction(MainWindow)
        self.actionTeste_Session_Log.setObjectName("actionTeste_Session_Log")
        self.actionFragebogen_ffnen = QtWidgets.QAction(MainWindow)
        self.actionFragebogen_ffnen.setObjectName("actionFragebogen_ffnen")
        self.menuNeu.addAction(self.actionNeue_Frage_erstellen)
        self.menuNeu.addAction(self.actionNeuen_Fragebogen_erstellen)
        self.menuNeu.addAction(self.actionNeue_Kategorie_erstellen)
        self.menuNeu.addAction(self.actionNewQuestionnaireCategory)
        self.menuDatei.addAction(self.menuNeu.menuAction())
        self.menuDatei.addSeparator()
        self.menuDatei.addAction(self.actionFragebogen_ffnen)
        self.menuDatei.addAction(self.actionDatei_importieren)
        self.menuDatei.addAction(self.actionFragebogen_exportieren)
        self.menuDatei.addSeparator()
        self.menuDatei.addAction(self.actionProgramm_beenden_2)
        self.menuBearbeiten.addAction(self.actionDatenbank_anzeigen_hinzuf_gen)
        self.menuBibliotheken.addAction(self.actionFragenbibliothek)
        self.menuBibliotheken.addAction(self.actionFragenkatalogbibliothek)
        self.menuBibliotheken.addAction(self.actionKategorien)
        self.menuBibliotheken.addAction(self.actionFragebogen_Kategorien)
        self.menuHilfe.addAction(self.actionHilfe_ffnen)
        self.menubar.addAction(self.menuDatei.menuAction())
        self.menubar.addAction(self.menuBearbeiten.menuAction())
        self.menubar.addAction(self.menuBibliotheken.menuAction())
        self.menubar.addAction(self.menuHilfe.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Anamnesebögen - Fragebogen-Editor"))
        self.MainNeueFrageButton.setText(_translate("MainWindow", "Neue Frage"))
        self.MainLibraryButton.setText(_translate("MainWindow", "Bibliothek"))
        self.MaintreeWidgetFK.setSortingEnabled(True)
        self.label.setText(_translate("MainWindow", "Fragenkatalog:"))
        self.mainopenqabutton.setText(_translate("MainWindow", "Öffnen"))
        self.MainSpeichernButton.setText(_translate("MainWindow", "Speichern"))
        self.MainAbbrechenButton.setText(_translate("MainWindow", "Leeren"))
        self.MainImportButton.setText(_translate("MainWindow", "Import"))
        self.MainExportButton.setText(_translate("MainWindow", "Export"))
        self.label_2.setText(_translate("MainWindow", "Fragen:"))
        self.mainedittreebutton.setText(_translate("MainWindow", "Bearbeiten"))
        self.maindeletetreebutton.setText(_translate("MainWindow", "Löschen"))
        self.MainFragebogenLabel.setText(_translate("MainWindow", "Fragebogen: "))
        self.MainKategorieLabel.setText(_translate("MainWindow", "Kategorie:"))
        self.MainSearchLine.setPlaceholderText(_translate("MainWindow", "Suche"))
        self.menuDatei.setTitle(_translate("MainWindow", "Datei"))
        self.menuNeu.setTitle(_translate("MainWindow", "Neu..."))
        self.menuBearbeiten.setTitle(_translate("MainWindow", "Bearbeiten"))
        self.menuBibliotheken.setTitle(_translate("MainWindow", "Bibliotheken"))
        self.menuHilfe.setTitle(_translate("MainWindow", "Hilfe"))
        self.actionFragenbibliothek.setText(_translate("MainWindow", "Fragenbibliothek"))
        self.actionFragenkatalogbibliothek.setText(_translate("MainWindow", "Fragebogenbibliothek"))
        self.actionKategorien.setText(_translate("MainWindow", "Fragen-Kategorien"))
        self.actionNeue_Datenbank_hinzuf_gen.setText(_translate("MainWindow", "Neue Datenbank hinzufügen"))
        self.actionDatenbank_anzeigen_hinzuf_gen.setText(_translate("MainWindow", "Datenbank anzeigen/hinzufügen"))
        self.actionFragebogen_speichern.setText(_translate("MainWindow", "Fragebogen speichern"))
        self.actionNeue_Frage_erstellen.setText(_translate("MainWindow", "Neue Frage erstellen"))
        self.actionNeue_Kategorie_erstellen.setText(_translate("MainWindow", "Neue Fragen-Kat. erstellen"))
        self.actionNeuen_Fragebogen_erstellen.setText(_translate("MainWindow", "Neuen Fragebogen erstellen"))
        self.actionProgramm_beenden.setText(_translate("MainWindow", "Programm beenden"))
        self.actionProgramm_beenden_2.setText(_translate("MainWindow", "Programm beenden"))
        self.actionHilfe_ffnen.setText(_translate("MainWindow", "Hilfe öffnen"))
        self.actionDatei_importieren.setText(_translate("MainWindow", "Fragebogen importieren"))
        self.actionFragebogen_exportieren.setText(_translate("MainWindow", "Fragebogen exportieren"))
        self.actionFragebogen_Kategorien.setText(_translate("MainWindow", "Fragebogen-Kategorien"))
        self.actionNewQuestionnaireCategory.setText(_translate("MainWindow", "Neue Fragebogen-Kat. erstellen"))
        self.actionTeste_Session_Log.setText(_translate("MainWindow", "Teste Session-Log"))
        self.actionFragebogen_ffnen.setText(_translate("MainWindow", "Fragebogen öffnen"))


if __name__ == "__main__":
    import sys

    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
