# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'DesignerChooseQA.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_ChooseQAWindow(object):
    def setupUi(self, ChooseQAWindow):
        ChooseQAWindow.setObjectName("ChooseQAWindow")
        ChooseQAWindow.resize(800, 300)
        self.centralwidget = QtWidgets.QWidget(ChooseQAWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        spacerItem = QtWidgets.QSpacerItem(40, 5, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.verticalLayout_2.addItem(spacerItem)
        self.label = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.verticalLayout_2.addWidget(self.label)
        spacerItem1 = QtWidgets.QSpacerItem(40, 5, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.verticalLayout_2.addItem(spacerItem1)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.tableChooseQA = QtWidgets.QTreeWidget(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        self.tableChooseQA.setFont(font)
        self.tableChooseQA.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.tableChooseQA.setLineWidth(2)
        self.tableChooseQA.setMidLineWidth(1)
        self.tableChooseQA.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAsNeeded)
        self.tableChooseQA.setSizeAdjustPolicy(QtWidgets.QAbstractScrollArea.AdjustToContents)
        self.tableChooseQA.setSelectionMode(QtWidgets.QAbstractItemView.ExtendedSelection)
        self.tableChooseQA.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectRows)
        self.tableChooseQA.setTextElideMode(QtCore.Qt.ElideLeft)
        self.tableChooseQA.setIndentation(0)
        self.tableChooseQA.setColumnCount(3)
        self.tableChooseQA.setObjectName("tableChooseQA")
        self.tableChooseQA.header().setDefaultSectionSize(50)
        self.tableChooseQA.header().setMinimumSectionSize(0)
        self.tableChooseQA.header().setStretchLastSection(False)
        self.verticalLayout.addWidget(self.tableChooseQA)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem2)
        self.choosedbintreebutton = QtWidgets.QPushButton(self.centralwidget)
        self.choosedbintreebutton.setObjectName("choosedbintreebutton")
        self.horizontalLayout.addWidget(self.choosedbintreebutton)
        self.closechoosedbbutton = QtWidgets.QPushButton(self.centralwidget)
        self.closechoosedbbutton.setObjectName("closechoosedbbutton")
        self.horizontalLayout.addWidget(self.closechoosedbbutton)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.verticalLayout_2.addLayout(self.verticalLayout)
        ChooseQAWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(ChooseQAWindow)
        QtCore.QMetaObject.connectSlotsByName(ChooseQAWindow)

    def retranslateUi(self, ChooseQAWindow):
        _translate = QtCore.QCoreApplication.translate
        ChooseQAWindow.setWindowTitle(_translate("ChooseQAWindow", "MainWindow"))
        self.label.setText(_translate("ChooseQAWindow", '<html><head/><body><p align="center">Bitte einen Fragebogen zum Öffnen auswählen:</p></body></html>'))
        self.tableChooseQA.headerItem().setText(0, _translate("ChooseQAWindow", "Kategorie"))
        self.tableChooseQA.headerItem().setText(1, _translate("ChooseQAWindow", "Name"))
        self.tableChooseQA.headerItem().setText(2, _translate("ChooseQAWindow", "Beschreibung"))
        self.choosedbintreebutton.setText(_translate("ChooseQAWindow", "Öffnen"))
        self.closechoosedbbutton.setText(_translate("ChooseQAWindow", "Abbrechen"))
