# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'DesignerRestoreSession.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_RestoreSession(object):
    def setupUi(self, RestoreSession):
        RestoreSession.setObjectName("RestoreSession")
        RestoreSession.resize(280, 90)
        RestoreSession.setStyleSheet("background-color:rgb(255, 255, 255)")
        self.centralwidget = QtWidgets.QWidget(RestoreSession)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.label = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label.sizePolicy().hasHeightForWidth())
        self.label.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.sessionrestoreButtonNo = QtWidgets.QPushButton(self.centralwidget)
        self.sessionrestoreButtonNo.setObjectName("sessionrestoreButtonNo")
        self.horizontalLayout.addWidget(self.sessionrestoreButtonNo)
        self.sessionrestoreButtonYes = QtWidgets.QPushButton(self.centralwidget)
        self.sessionrestoreButtonYes.setObjectName("sessionrestoreButtonYes")
        self.horizontalLayout.addWidget(self.sessionrestoreButtonYes)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.verticalLayout.setStretch(0, 2)
        self.verticalLayout.setStretch(1, 1)
        self.verticalLayout_2.addLayout(self.verticalLayout)
        # RestoreSession.setCentralWidget(self.centralwidget)

        self.retranslateUi(RestoreSession)
        QtCore.QMetaObject.connectSlotsByName(RestoreSession)

    def retranslateUi(self, RestoreSession):
        _translate = QtCore.QCoreApplication.translate
        RestoreSession.setWindowTitle(_translate("RestoreSession", "Anamnesebögen - Information"))
        self.label.setText(
            _translate("RestoreSession", '<html><head/><body><p align="center">Es wurde ein Sicherungspunkt gefunden.<br/>Soll die alte Sitzung wiederhergestellt werden?</p></body></html>')
        )
        self.sessionrestoreButtonNo.setText(_translate("RestoreSession", "Nein"))
        self.sessionrestoreButtonYes.setText(_translate("RestoreSession", "Ja"))
